apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: shop
  destination: { server: https://kubernetes.default.svc, namespace: shop }
  source:
    repoURL: https://github.com/automatewithcharan/gitops-shop.git
    targetRevision: main
    path: environments/dev/ingress-manifests
  syncPolicy: { automated: { prune: true, selfHeal: true } }
