apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ing
  namespace: shop
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - charanthirumalla.online
    secretName: web-tls   # cert-manager will create this
  rules:
  - host: charanthirumalla.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: { name: web-podinfo, port: { number: 9898 } }
      - path: /api
        pathType: Prefix
        backend:
          service: { name: api-podinfo, port: { number: 9898 } }

